### ISSUE TITLE
Move to Suave itself?

### ISSUE THREAD

**Issue by jasonzoladz** [dustinmoris/Suave.AspNetCore#4]
Have you had any discussions with Suave's maintainers about making this an official thing?  The prospect of using Suave and piggybacking on Kestrel is exciting.

**Comment by dustinmoris** [comment]
Hi, no actually I haven't spoken with them, but I'd be more than happy to do what you suggested. If @ademar or @haf want I can help them to move it to Suave and I could even re-write the C# code in F# now that I know what needs to be done. It was easier to do it in C#, because it allowed me to use Visual Studio and debugging of .NET Core, but now that it is working I can reverse engineer it into F#, which would make future maintenance easier (assuming that the tooling for .NET Core F# will improve eventually).

**Comment by ademar** [comment]
Thanks Dustin, you are welcome to move it under our organization. I'll send you an invitation.

I am OK with it staying in C# but it is your project you do whatever you want :)

**Comment by haf** [comment]
We can make it a top-level project of SuaveIO on github, but I don't think we should merge it into the main repo. That way @dustinmoris can keep the maintenance and ownership of this repo.

**Comment by dustinmoris** [comment]
cool guys. I will do it this way, on my way to work now so will make the move to SuaveIO over this weekend! Cheers!

**Comment by jasonzoladz** [comment]
Thanks man.  I really appreciate it.

**Comment by dustinmoris** [comment]
Done

**Comment by haf** [comment]
You're now admin for it, too.
